=== sergeinack3/PowerCare/modules/dPpatients/resources/ConstantSpec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.openxtrem.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.openxtrem.com" xmlns:ox="http://www.openxtrem.com">

  <xs:element name="constantSpec">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="constants">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="constant" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="uniqueConstantId">
            <xs:selector xpath="ox:constant"/>
            <xs:field xpath="@id"/>
          </xs:unique>
          <xs:unique name="uniqueConstantCode">
            <xs:selector xpath="ox:constant"/>
            <xs:field xpath="@code"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="constant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="typeNameConstant"/>
        <xs:element name="unit" type="xs:string"/>
        <xs:element name="value_class" type="typeValueClass"/>
        <xs:element name="category" type="typeCategory"/>
        <xs:element name="min_value" type="xs:string" minOccurs="0"/>
        <xs:element name="max_value" type="xs:string" minOccurs="0"/>
        <xs:element name="alterable" type="xs:boolean" minOccurs="0"/>
        <xs:element name="alerts" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="alert" type="typeAlert" maxOccurs="3" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="list" type="typeList" minOccurs="0"/>
        <xs:element name="formule" type="xs:string" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="code" type="xs:string"/>
      <xs:attribute name="id" type="typeIdConstant"/>
      <xs:attribute name="period" type="xs:int"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="typeNameConstant">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeValueClass">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CValueInt"/>
      <xs:enumeration value="CValueInterval"/>
      <xs:enumeration value="CValueText"/>
      <xs:enumeration value="CValueEnum"/>
      <xs:enumeration value="CValueFloat"/>
      <xs:enumeration value="CStateInterval"/>
      <xs:enumeration value="CDateTimeInterval"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeCategory">
    <xs:restriction base="xs:string">
      <xs:enumeration value="physio"/>
      <xs:enumeration value="biolo"/>
      <xs:enumeration value="activity"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="typeAlert">
    <xs:sequence>
      <xs:group ref="alert_seuil_bas" minOccurs="0"/>
      <xs:group ref="alert_seuil_haut" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="typeIdAlerte"/>
  </xs:complexType>

  <xs:group name="alert_seuil_bas">
    <xs:sequence>
      <xs:element name="seuil_bas" type="xs:string"/>
      <xs:element name="text_bas" type="xs:string"/>
    </xs:sequence>
  </xs:group>

  <xs:group name="alert_seuil_haut">
    <xs:sequence>
      <xs:element name="seuil_haut" type="xs:string"/>
      <xs:element name="text_haut" type="xs:string"/>
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="typeList">
    <xs:restriction base="xs:string">
      <xs:pattern value="(\w|)+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="typeIdConstant">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeIdAlerte">
    <xs:restriction base="typeIdConstant">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== sergeinack3/PowerCare/modules/dPpatients/resources/ConstantSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<constantSpec xmlns="http://www.openxtrem.com" xsd:schemaLocation="http://www.openxtrem.com ConstantSpec.xsd"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance">
  <constants>
    <constant code="height" id="1" period="0">
      <name>height</name>
      <unit>cm|m *100|mm /10</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <max_value>300</max_value>
    </constant>

    <constant code="heartrate" id="2" period="0">
      <name>heartrate</name>
      <unit>bpm</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <max_value>250</max_value>
      <alerts>
        <alert id="1">
          <seuil_bas>50</seuil_bas>
          <text_bas>Poul faible</text_bas>
        </alert>
        <alert id="2">
          <seuil_haut>180</seuil_haut>
          <text_haut>Poul haut</text_haut>
        </alert>
        <alert id="3">
          <seuil_haut>205</seuil_haut>
          <text_haut>Poul très haut</text_haut>
        </alert>
      </alerts>
    </constant>

    <constant code="dailyactivity" id="3" period="86400">
      <name>dailyactivity</name>
      <unit>step</unit>
      <value_class>CValueInt</value_class>
      <category>activity</category>
      <min_value>0</min_value>
      <max_value>1000000</max_value>
      <alerts>
        <alert id="1">
          <seuil_bas>100</seuil_bas>
          <text_bas>Peu d'activité dans la journée</text_bas>
        </alert>
      </alerts>
    </constant>

    <constant code="hourlyactivity" id="4" period="3600">
      <name>hourlyactivity</name>
      <unit>step</unit>
      <value_class>CValueInt</value_class>
      <category>activity</category>
      <min_value>0</min_value>
      <max_value>100000</max_value>
    </constant>

    <constant code="dailysleep" id="5" period="86400">
      <name>dailysleep</name>
      <unit>sec|min /60|h /3600</unit>
      <value_class>CDateTimeInterval</value_class>
      <category>biolo</category>
      <alerts>
        <alert id="1">
          <seuil_bas>28800</seuil_bas>
          <text_bas>Vous dormez peu</text_bas>
          <seuil_haut>43200</seuil_haut>
          <text_haut>Vous dormez beaucoup</text_haut>
        </alert>
      </alerts>
    </constant>

    <constant code="hourlysleep" id="6" period="0">
      <name>hourlysleep</name>
      <unit>sec|min /60</unit>
      <value_class>CStateInterval</value_class>
      <category>biolo</category>
      <list>0|1|2|3|4|5|6</list>
    </constant>

    <constant code="lightsleepduration" id="7" period="86400">
      <name>lightsleepduration</name>
      <unit>sec|min /60|h /3600</unit>
      <value_class>CValueInt</value_class>
      <category>biolo</category>
      <min_value>0</min_value>
      <max_value>86400</max_value>
    </constant>

    <constant code="deepsleepduration" id="8" period="86400">
      <name>deepsleepduration</name>
      <unit>sec|min /60|h /3600</unit>
      <value_class>CValueInt</value_class>
      <category>biolo</category>
      <min_value>0</min_value>
      <max_value>86400</max_value>
    </constant>

    <constant code="wakeupduration" id="9" period="86400">
      <name>wakeupduration</name>
      <unit>sec|min /60|h /3600</unit>
      <value_class>CValueInt</value_class>
      <category>biolo</category>
      <min_value>0</min_value>
      <max_value>86400</max_value>
    </constant>

    <constant code="weight" id="10" period="0">
      <name>weight</name>
      <unit>g|kg *1000</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <max_value>8000000</max_value>
    </constant>

    <constant code="remduration" id="11" period="86400">
      <name>remduration</name>
      <unit>sec|min /60|h /3600</unit>
      <value_class>CValueInt</value_class>
      <category>biolo</category>
      <min_value>0</min_value>
      <max_value>86400</max_value>
    </constant>

    <constant code="imc" id="12" period="0">
      <name>imc</name>
      <unit>g/mm²</unit>
      <value_class>CValueInt</value_class>
      <category>biolo</category>
      <formule>(([$weight]*10) / pow(2,[$height])</formule>
    </constant>

    <constant code="dailyheartrate" id="13" period="86400">
      <name>heartrate</name>
      <unit>bpm</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <max_value>250</max_value>
      <alterable>1</alterable>
    </constant>

    <constant code="heartrateinterval" id="14" period="86400">
      <name>heartrate</name>
      <unit>bpm</unit>
      <value_class>CValueInterval</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <max_value>250</max_value>
    </constant>

    <constant code="dailydistance" id="15" period="86400">
      <name>distance</name>
      <unit>m</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
      <alterable>1</alterable>
    </constant>

    <constant code="systole" id="16" period="0">
      <name>systole</name>
      <unit>mm/Hg|cm/Hg /10</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
    </constant>

    <constant code="diastole" id="17" period="0">
      <name>diastole</name>
      <unit>mm/Hg|cm/Hg /10</unit>
      <value_class>CValueInt</value_class>
      <category>physio</category>
      <min_value>0</min_value>
    </constant>

    <constant code="temperature" id="18" period="0">
      <name>temperature</name>
      <unit>°C|°F (($a-32)*(5/9))</unit>
      <value_class>CValueFloat</value_class>
      <category>physio</category>
      <min_value>35</min_value>
      <max_value>43</max_value>
    </constant>
  </constants>
</constantSpec>
